### ISSUE TITLE
Cannot read property 'chunk' of undefined

### ISSUE THREAD

**Issue by danielflippance** [faceleg/node-pluploader#4]
I'm seeing the following error when using the node-plupload sample code from the README.md along with the plupload custom sample from http://www.plupload.com/docs/Getting-Started#full-example:

    Process Error: TypeError: Cannot read property 'chunk' of undefined
    TypeError: Cannot read property 'chunk' of undefined
        at /blah/blah/node_modules/node-pluploader/index.js:118:16
        at /blah/blah/node_modules/node-pluploader/node_modules/multiparty/index.js:116:9
        at /blah/blah/node_modules/node-pluploader/node_modules/multiparty/index.js:108:9
        at process._tickDomainCallback (node.js:459:13)

index.js 118 is the following code:

    116: form.parse(req, function(err, fields, files) {
    117:
    118: if (!fields.chunk) {

Any idea why fields would be undefined? I'm using ExpressJS 4.

**Comment by faceleg** [comment]
Is `err` populated? I see it is passed into the function on https://github.com/faceleg/node-pluploader/blob/master/index.js#L116 but I never wrote code to check it - this is where I would start

**Comment by danielflippance** [comment]
Yep: "Error: stream ended unexpectedly". Looking into what might cause this...

**Comment by faceleg** [comment]
Did you ever get to the bottom of this?

**Comment by MartinMalinda** [comment]
I have the same issue and the err variable contains: ```{ [Error: stream ended unexpectedly] status: 400, statusCode: 400 }```

**Comment by VicSoft** [comment]
Hello folks. This problem was resolved for me by checking if path to save file is correct. It wasn't for me, so i've changed it and is working very well. I hope I've helped

**Comment by faceleg** [comment]
@VicSoft was that a change in your code or is there a change required in this library?

**Comment by VicSoft** [comment]
on my own code. When i instantiate the library i have to pass the string value from my directory to uploadDir key on object param from Pluploader class, something like: /var/www/mywebsitedir.com/public/files/ ... this path was with read only permissions or wrong.

**Comment by faceleg** [comment]
Right. Thanks for the reply. I suppose it would be best if pluploader reported a better error in this situation.

**Comment by VicSoft** [comment]
Yeah, you're welcome. This error isn't specifies rightly the causes. But i think that is related with the folder to save file. Good lucky

**Comment by sagnol** [comment]
check plupload _multipart_ option on client side.
multiparty module check content-type if is multipart/form-data.
so  plupload _multipart_ option have to set 'true'.


[https://github.com/expressjs/node-multiparty/blob/master/index.js#L32](https://github.com/expressjs/node-multiparty/blob/master/index.js#L32)
