### ISSUE TITLE
Add unit tests, travis 

### ISSUE THREAD

**Issue by faceleg** [faceleg/node-pluploader#5]
To support issue reported: 

```TEXT
node-pluploader can't run in node V4.1.1 ?

module.js:355
Module._extensions[extension](this, filename);
^

Error: Module version mismatch. Expected 46, got 14.
at Error (native)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/mydata/test/node_modules/node-pluploader/node_modules/mmmagic/index.js:3:13)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/mydata/test/node_modules/node-pluploader/index.js:6:13)
at Module._compile (module.js:434:26)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
```

**Comment by faceleg** [comment]
Resolved by user deleting their `node_modules` directory and running `npm install`
